package com.mycompany.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.mycompany.entity.Product;
import com.mycompany.services.ServiceProduct;
import java.util.ArrayList;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
//        if(current != null){
//            current.show();
//            return;
//        }
        Form hi = new Form("Product", BoxLayout.y());
        hi.add(new Label("Product"));
//        hi.show();
 if(current != null){
            current.show();
            return;
        }
//        try {
                   new SplashForm(theme).show();
//            new AffichProducts().show();
//            new AddProdForm().show();
//        ServiceProduct sp= new ServiceProduct();
//       ArrayList<Product> products=sp.affichageProduct2();
//       hi.add(new Label(products.toString()));
//       hi.show();
//        } catch (IOException ex) {
//            //  Logger.getLogger(MyApplication.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
